### PR TITLE
yggtorrent update

### PR DESCRIPTION
**Pull request by ylon**
website is not fully up . haven't checked login . just done selectors . results like this :
```
  { title: 'Game.of.Thrones.S02.MULTI.Extra.Bonus.1080p.Bluray.HEVC.AAC.5.1.x265',
    time: 2017-07-29T08:37:45.000Z,
    seeds: 32,
    peers: 7,
    size: '18.26GB',
    desc: 'https://yggtorrent.is/torrent/filmvidéo/série-tv/43614-game+of+thrones+s02+multi+extra+bonus+1080p+bluray+hevc+aac+5+1+x265',
    id: '43614',
    provider: 'Yggtorrent',
    link: 'https://yggtorrent.is/engine/download_torrent?id=43614' }
```

### CODE REVIEW

**Comment by ylon** [comment]
I have checked login is ok.

**Comment by YouriT** [comment]
Indeed, just tested it out, it works fine.

@ylon you should nevertheless do a little `prettier --write lib/providers/yggtorrent.js` on your changes.

@JimmyLaurent awaiting anything before merging this?

**Comment by YouriT** [comment]
The config is autoloaded from `package.json` theoretically according to the [docs](https://prettier.io/docs/en/configuration.html)

**Comment by ylon** [comment]
@YouriT ok. i run the command in my home, not the project folder, thxs.

**Comment by YouriT** [comment]
You should run it from the project root folder. Where the package.json is :)

**Comment by JimmyLaurent** [comment]
Good job @ylon, It's merged and published, thanks.

**Pull request merged**
